### ISSUE TITLE
[Job Launcher Frontend] Sign message request appears right after transaction was approved on Metamask.

### ISSUE THREAD

**Issue by Dzeranov** [humanprotocol/human-protocol#2080] opened 2024-05-29 08:43 UTC
**Describe the bug**
Upon sending tokens to the Job Launcher, sign message request appears right after it was approved on Metamask.
By clicking it right away it will cause an error on a backend because transaction doesn't exist yet.

**To Reproduce**
1. Go to Job Launcher
2. Create a job and fund it with your crypto wallet.
3. Click on sign message right after modal window appears

**Expected behavior**
Sign message modal shouldn't appear before transcation is actually approved on chain.

**Comment by portuu3** [comment] 2024-05-30 06:56
Duplicate of #2085

**Closed by portuu3** 2024-05-30 06:56 UTC
Labels: bug
