### ISSUE TITLE
[CVAT][Exchange Oracle] Unit and integration tests

### ISSUE THREAD

**Issue by Dzeranov** [humanprotocol/human-protocol#645] opened 2023-07-06 09:17 UTC
**Description**
Need to add more unit and service tests to Exchange Oracle

**Motivation**
To improve code test coverage.

**Implementation details** 
1. Add tests for cron jobs.
2. Add unit tests for `/src/modules/cvat/helpers.py`

**Comment by portuu3** [comment] 2023-07-17 10:35
duplicate of #672

**Closed by portuu3** 2023-07-17 10:35 UTC
Labels: CVAT
